### ISSUE TITLE
Running from command line

### ISSUE THREAD

**Issue by wummel** [wummel/linkchecker#100]
Converted from [SourceForge issue 1216092](http://sourceforge.net/support/tracker.php?aid=1216092), submitted by nobody

```
curses.setupterm()
```

error: setupterm: could not find terminfo database
System info:
LinkChecker 2.9
Python 2.4.1 (#2, Jun  6 2005, 16:56:01) 
[GCC 2.95.4 20020320 [FreeBSD]] on freebsd4

*******\* LinkChecker internal error, bailing out ********

URL        '/channel/series59.html' (cached)
Name       '\nBroadcast Dates'
Parent URL
http://www.learner.org/catalog/series59.html, line 162,
col 1
Real URL   http://www.learner.org/channel/series59.html
Result     Error: (7, 'No address associated with
hostname')

linkchecker --file-output=html/test.html
--recursion-level=4 http://www.learner.org/

**Comment by dynamiclogisticsetco** [comment]
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Length: 12585
Content-Type: application/json
Date: Tue, 14 Nov 2017 14:33:14 GMT
Keep-Alive: timeout=10, max=1000
Last-Modified: Mon, 07 Aug 2017 20:46:05 GMT
Server: Apache/2.4.26 (Unix)

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Host: ftp.gnome.org
Referer: http://ftp.gnome.org/pub/GNOME/sources/glade3/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
