### ISSUE TITLE
error: can't copy 'doc/html/lccollection.qhc' on OSX

### ISSUE THREAD

**Issue by wummel** [wummel/linkchecker#272]
Converted from [SourceForge issue 3263746](http://sourceforge.net/support/tracker.php?aid=3263746), submitted by richb-hanover

Attempting to install LinkChecker 6.6 on OSX 10.6.7, the final error line of the installation was:

error: can't copy 'doc/html/lccollection.qhc': doesn't exist or not a regular file

The software seems to be working fine - just want to report this message. I have attached the entire output

**Comment by piggy666** [comment]
make app
make: **\* No rule to make target `app'.  Stop.

I checked the Makefile. There is no target 'app' defined.......

**Comment by edmond-chhung** [comment]
@piggy666 i believe @wummel meant run make all inside doc/html.  I went through the code and saw that the master branch doesnt contain doc/html. @wummel must have separated the branches for linux. I have forked the project and taken some of the updates from other maintainers and added the doc/html files back into my repo. I have only tried mine on ubuntu but it seems to be working.
