### ISSUE TITLE
LinkChecker detects false 404's in Wikis

### ISSUE THREAD

**Issue by wummel** [wummel/linkchecker#280]
Converted from [SourceForge issue 3300251](http://sourceforge.net/support/tracker.php?aid=3300251), submitted by None

Checking a mediawiki site with LinkChecker and iot reports a lot of false psotivie 404's.

It appears that ":"'s in the link, i.e.

https://wiki.example.org/foo/index.php/Something:Here

Confuses LinkChecker, it converts it to percent encoding:

https://wiki.example.org/foo/index.php/Something%3AHere

which works in a browser, but for whatever reason LinkChecker fails on it and thinks it is 404. This appears to happen across multiple MediaWiki sites. If you need more specifics please contact me kurt@seifried.org

**Comment by stefanct** [comment]
I can confirm this with the LinkChecker 9.3 (released 16.7.2014) on Ubuntu and I'd rather not build it myself (yet).
