### ISSUE TITLE
Getting ResponseNotReady for links that should work

### ISSUE THREAD

**Issue by praus** [wummel/linkchecker#376]
I ran LinkChecker on our site (http://icpc.baylor.edu) and I'm getting a bunch of ResponseNotReady errors on URLs that load fine in browser on wget. In fact, when I run LinkChecker with the misbehaving URL as an argument, it seems to work.

This is how the error looks like in the log:

```
URL        `/javax.faces.resource/cm.css.icpc;jsessionid=loKtsoi+PClT42Lmkxiu5-86?ln=stylesheet'
Parent URL http://cmng.ecs.baylor.edu/public/worldMap/1347, line 2, col 435
Real URL   http://cmng.ecs.baylor.edu/javax.faces.resource/cm.css.icpc;jsessionid=loKtsoi+PClT42Lmkxiu5-86?ln=stylesheet
Check time 1.666 seconds
Result     Error: ResponseNotReady: State Request-sent, Response <HTTPResponse status=302 reason=Found chunked=0 length=0>
```

The command I'm running is this:
`linkchecker --no-follow-url='(.*)jsessionid=(.*)' -r 4 http://icpc.baylor.edu/`

I found similar but 3 years old bug report that's closed as Fixed:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=512358

I'm using LinkChecker 8.2 on RHEL 6.3 with Python 2.7.3. Am I doing something wrong?

**Comment by wbolster** [comment]
fwiw, server responses without a content-length header combined with a client that uses keep-alive can also result in errors like these.
