### ISSUE TITLE
certificate verify failed even ignorewarnings=https-certificate-error

### ISSUE THREAD

**Issue by okv** [wummel/linkchecker#387]
Hi there!

For url's with self-signed certificate I always get error

```
Result     Error: SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

even

```
ignorewarnings=https-certificate-error
```

is set at the config

LinkChecker 8.2 Linux

**Comment by eBeyond** [comment]
Still the same with 9.3 :(

**Comment by Pablohn26** [comment]
Yes, still the same :(

**Comment by tseweb** [comment]
This is not an error and works as designed.
Simply go to Edit > Options and edit the configuration file.
In the `[checking]` section uncomment `#sslverify=1` and change it to `sslverify=0`
Now you can check the links on websites using self-signed certificates.

**Comment by rajtester** [comment]
I am getting SSL 510 error. I followed tseweb, even though :(
Help will be appreciated.

**Comment by viavario** [comment]
@rajtester do not forget to uncomment that line by removing the hashtag at the beginning of the line.

**Comment by Jakobkv** [comment]
Hi i got a problem with my linkchecker 9.3 after I have updatet my website to SSL!

I have tryed to change from #sslverify=1 to sslverify=0 but then I just get Error 403 forbidden!

My site is a linkportal and I really need this to be working again ?

What can I do ?

Skype: kvonne1

**Comment by trueliarx** [comment]
same problem on 9.3

**Comment by epiphanizer** [comment]
Also had the problem on 9.3, setting ~/.linkchecker/linkcheckrerc's verifyssl=0 got me up & running at least.

**Comment by SpikePy** [comment]
I'm also having this problem but setting verifyssl=0 didn't help.

**Comment by dbegle** [comment]
Same issue here, but solved using steps tseweb (thanks!) described above.  Here's a step-by-step:

1. uncomment the line with #sslverify=1 (delete the hash mark) **If you don't remove the hash mark, nothing will happen when you run linkcheck again.**  
2. change sslverify=**1** to sslverify=**0**
3. Save the file
4. Run linkchecker again

**Comment by localhorst** [comment]
> This is not an error and works as designed.
> Simply go to Edit > Options and edit the configuration file.
> In the `[checking]` section uncomment `#sslverify=1` and change it to `sslverify=0`
> Now you can check the links on websites using self-signed certificates.

I can confirm that this works with v 9.3 on Windows.

**Comment by qiuminwei** [comment]
> Same issue here, but solved using steps tseweb (thanks!) described above. Here's a step-by-step:
> 
> 1. uncomment the line with #sslverify=1 (delete the hash mark) **If you don't remove the hash mark, nothing will happen when you run linkcheck again.**
> 2. change sslverify=**1** to sslverify=**0**
> 3. Save the file
> 4. Run linkchecker again

Also need to make sure that the configuration file used by the command is same with the modified configuration file, I fixed like this:
```
sudo sed -i 's/#sslverify=1/sslverify=0/g' /usr/share/linkchecker/linkcheckerrc
linkchecker --config=/usr/share/linkchecker/linkcheckerrc https://yoururl/
```

**Comment by aizad02** [comment]
> Also had the problem on 9.3, setting ~/.linkchecker/linkcheckrerc's verifyssl=0 got me up & running at least.

Thanks man! yours did solve the problem.
