### ISSUE TITLE
OSX .dmg missing

### ISSUE THREAD

**Issue by llanverygranger** [wummel/linkchecker#392]
Hi

I can't seem to find the .dmg install file for OSX.

Is this available? And if not how do I build it on OSX 10.8?

I couldn't see a way to contact the author of the software directly, so I placed my message here. Apologies if this is in the wrong place!

Many thanks
Mike

**Comment by splorp** [comment]
I reinstalled py2app as well, but it didn’t change anything. I still think is has something to do with the localization strings on my end.

Can you Dropbox me a copy of your compiled app to test on my Snow Leopard system?

**Comment by natke** [comment]
Sure. You can get it here:
https://www.dropbox.com/sh/6urh79ijnzyuz5d/AABNa6snL0zbqt7JSIRgjZCaa?dl=0.
Let me know how you go.

**Comment by splorp** [comment]
Thanks.

The .dmg mounts fine, but I’m seeing the following error in the console log. I see the same thing when launch my incomplete build of the Mac OS X app. Since the build isn’t being completed due to [this burp while copying files](https://github.com/wummel/linkchecker/issues/568) into the app bundle, the Python framework isn’t being copied into the package either.

```
15-01-02 3:29:11 PM   LinkChecker[99500] A Python runtime not could be located. \
     You may need to install a framework build of Python, or edit the PyRuntimeLocations array in this application's Info.plist file.
15-01-02 3:29:19 PM  com.apple.launchd.peruser.501[275]	([0x0-0xcb2cb2].org.pythonmac.LinkChecker[99500]) \
     Exited with exit code: 255
```

**Comment by natke** [comment]
I've done a bit more reading on py2app and it seems that it builds either a
semi-standalone app, or a standalone one. From what I read, the apple
version of python only builds the semi-standalone. I re-installed python
from python.org and it now seems to be building a standalone version, but
it is reporting modules that it can't find, including the one that I get
the error reported on:

Modules not found (unconditional imports):

 * OpenSSL (linkcheck.checker.const,
requests.packages.urllib3.contrib.pyopenssl)

 * PyQt4 (/usr/local/linkcheckerTest/linkchecker-gui, PyQt4, linkcheck.gui,
linkcheck.gui.checker, linkcheck.gui.contextmenu, linkcheck.gui.debug,
linkcheck.gui.editor, linkcheck.gui.editor_qsci, linkcheck.gui.editor_qt,
linkcheck.gui.help, linkcheck.gui.lineedit, linkcheck.gui.linkchecker_rc,
linkcheck.gui.linkchecker_ui_debug, linkcheck.gui.linkchecker_ui_editor,
linkcheck.gui.linkchecker_ui_main, linkcheck.gui.linkchecker_ui_options,
linkcheck.gui.options, linkcheck.gui.projects, linkcheck.gui.recentdocs,
linkcheck.gui.settings, linkcheck.gui.syntax, linkcheck.gui.updater,
linkcheck.gui.urlmodel, linkcheck.gui.urlsave)


etc etc (there are a lot of these reported)

I guess these need to be manually installed?

**Comment by xandrani** [comment]
How do I unsubscribe from these emails?

Thanks :)

**Comment by splorp** [comment]
@xandrani There’s an unsubscribe button on the right side of this page.

![screenshot 2015-01-02 18 35 16](https://cloud.githubusercontent.com/assets/29835/5601179/29089dc8-92ae-11e4-8887-b83d694eefb5.png)

**Comment by harry-wood** [comment]
There's still a reference to a .dmg file here: https://github.com/wummel/linkchecker/blob/master/doc/install.txt#L26  and no dmg file anywhere. Maybe  install.txt should point mac users at this discussion or something

**Comment by rsyring** [comment]
Would also like to see a .dmg built.  Can this issue get re-opened?

**Comment by alvaro-rm** [comment]
I have the same problem. Where is the .dmg file?

**Comment by kaig78** [comment]
Same issue

**Comment by laurel** [comment]
:+1: for a .dmg

**Comment by mcollinsblog** [comment]
Just download Wineskin Winery, create a new wrapper and install the EXE through it. Takes ~5 minutes.

**Comment by splorp** [comment]
Thanks @mcollinsblog … this sounds like a great solution.

For those not familiar with [Wineskin Winery](http://wineskin.urgesoftware.com/tiki-index.php), it is an open source utility which provides a Mac OS X “wrapper” around Windows applications, allowing them to run on Snow Leopard and later.

**Comment by splorp** [comment]
I can confirm that this method works great.

**Comment by mrgauthier** [comment]
Install with pip.  use the --user option on El Capitan and greater:

pip install --user LinkChecker
