### ISSUE TITLE
How to check existence of image files only?

### ISSUE THREAD

**Issue by ghost** [wummel/linkchecker#502]
This isn't an issue or bug...because I think I can do what I want with a configuration file edit.

Background:  website has 2.5 GB of mostly text over 400K of html files.  

Situation: Linkchecker is checking everything--and that is taking a huge amount of time (several hours). At the moment, I don't care about anchor-links, only img links.

Question: How can I get link checker to check only for the existence of image files? I don't care about the rest. This would speed up my linkcheck runs considerably.

**Comment by meu-io** [comment]
I think that works on a site where each page URL ends in .html extension (or png/jpg/...) however if one is scanning a content management system or other site using friendly URLs (pages having names but no .html/.php extension) what sort of linkchecker command line invocation might one use recursively check a large site but to only check (entire site) for broken images (jpg/jpeg/gif/png) ?

By "checking image files" I mean, not checking for broken links to other html content pages, but only looking for broken image links but recursively crawling an entire site.
