### ISSUE TITLE
error: can't copy 's': doesn't exist or not a regular file with setup.py install --home on Debian testing

### ISSUE THREAD

**Issue by a3nm** [wummel/linkchecker#568]
Hi,

I'm trying to compile linkchecker on Debian testing to work around https://github.com/wummel/linkchecker/issues/566 and trying to install it as a normal user, but I am encountering a strange error.

Following doc/install.txt, I have installed the required dependencies and run:

```
make -C doc/html                       
python setup.py sdist --manifest-only
python setup.py build
mkdir -p /home/a3nm/apps/linkchecker_install/lib/python
PYTHONPATH="/home/a3nm/apps/linkchecker_install/lib/python/:$PYTHONPATH" PATH="/home/a3nm/apps/linkchecker_install/bin/:$PATH" python setup.py install --home /home/a3nm/apps/linkchecker_install
```

The last command fails with the following strange error:

```
error: can't copy 's': doesn't exist or not a regular file
```

Nothing suspicious happens in the previous commands except for a warning when building the manifests and a number of compile warnings. Here is the output of the first phase, in case it is relevant:

```
creating /home/a3nm/apps/linkchecker2/_LinkChecker_configdata.py
running sdist
running check
warning: MySdist: standard file not found: should have one of README, README.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'MANIFEST'
```

What could possibly be going wrong?

**Comment by splorp** [comment]
@a3nm Can you post a bit more of the build log surrounding the `error: can’t copy ...` message?

I’d like to compare it to the output from my build, seeing if the build stops during the same sequence.

Thanks.

**Comment by a3nm** [comment]
Here's the full log: http://paste.fulltxt.net/hTf

**Comment by splorp** [comment]
Thanks.

It appears that both builds are breaking when attempting to add the localization files to the app bundle.

**Comment by MassimoDIFA** [comment]
same error on OSX 10.10.3 with Python 2.7.6

'copying file config/linkchecker.apache2.conf -> /linkchecker/dist/LinkChecker.app/Contents/Resources/share/linkchecker/examples/linkchecker.apache2.conf
copying file s -> /linkchecker/dist/LinkChecker.app/Contents/Resources/po/de.mo/s
error: [Errno 2] s: 'No such file or directory'
make: *** [app] Error 1'

any idea?

**Comment by MassimoDIFA** [comment]
I have also tried to build the unix executable but it didn't work.

**Comment by velkro** [comment]
Same error on OSX 10.10.4 / Python 2.7.10
```
copying file cgi-bin/lconline/check.js -> /linkchecker/dist/LinkChecker.app/Contents/Resources/share/linkchecker/examples/check.js
copying file cgi-bin/lc.wsgi -> /linkchecker/dist/LinkChecker.app/Contents/Resources/share/linkchecker/examples/lc.wsgi
copying file config/linkchecker.apache2.conf -> /linkchecker/dist/LinkChecker.app/Contents/Resources/share/linkchecker/examples/linkchecker.apache2.conf
copying file s -> /linkchecker/dist/LinkChecker.app/Contents/Resources/po/de.mo/s
error: [Errno 2] s: 'No such file or directory'
make: *** [app] Error 1
```

**Comment by lars30** [comment]
Same error for me OSX 10.10.4 / (Brew) Python 2.7.10:
copying file cgi-bin/lc.wsgi -> /Users/larry/dev/linkchecker/dist/LinkChecker.app/Contents/Resources/share/linkchecker/examples/lc.wsgi
copying file config/linkchecker.apache2.conf -> /Users/larry/dev/linkchecker/dist/LinkChecker.app/Contents/Resources/share/linkchecker/examples/linkchecker.apache2.conf
copying file s -> /Users/larry/dev/linkchecker/dist/LinkChecker.app/Contents/Resources/po/de.mo/s
error: [Errno 2] s: 'No such file or directory'
make: *** [app] Error 1

**Comment by davidneudorfer** [comment]
+1

**Comment by aseidlitz** [comment]
+1

**Comment by loweryaustin** [comment]
I'm getting the same thing on El Capitan
copying file s -> /Users/XXXX/Downloads/linkchecker/dist/LinkChecker.app/Contents/Resources/po/de.mo/s
error: [Errno 2] s: 'No such file or directory'
make: *** [app] Error 1

**Comment by roshanparmar** [comment]
I am getting the same thing
copying config/linkchecker.apache2.conf -> build/bdist.linux-x86_64/egg/share/linkchecker/examples
creating build/bdist.linux-x86_64/egg/po
creating build/bdist.linux-x86_64/egg/po/fr.mo
error: can't copy 's': doesn't exist or not a regular file

**Comment by nateq314** [comment]
+1  same here

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists

**Comment by a3nm** [comment]
Thanks for pointing this out. I have tested this on your fork and I can compile and install it without any issues now, so this issue can indeed be closed.
