### ISSUE TITLE
Instructions for using with Travis CI / GitHub pages

### ISSUE THREAD

**Issue by fulldecent** [wummel/linkchecker#573]
Cross post to https://stackoverflow.com/questions/28219945/travis-ci-with-github-pages-linkchecker

I am hosting pages on GitHub Pages. These use Jekyll, but that shouldn't matter.

Since we have source code management for the web pages and even a publishing and hosting... why not add CI!

Is there a best practice for implementing a link checker using Travis CI scenario. Also, practically, is this the "right" thing to do since may use a lot of resources?

**Comment by Autodidact24** [comment]
+1. I have a similar question. I've a project, the documentation of which are generated using http://www.mkdocs.org/. How do I implement a link checker ?

**Comment by fulldecent** [comment]
Best practices are now documented here https://github.com/fulldecent/html-website-template and so easy to set up. Closing, don't need this any more.
