### ISSUE TITLE
"Short" logging for "data:" urls

### ISSUE THREAD

**Issue by htgoebel** [wummel/linkchecker#588]
Please add some "short" logging format for "data:" URLs.

This could be done by shortening the URL by replacing the actual data by a /md5-)checksum like: `data:image/jpeg;base64 -- md5(...)`
### Description of error

"data:" urls trend to be _very_ long, because they contain the data itself, which often are pictures and easily several KB long. When logging them do the log-file unchanged, lines become too long for post-processing. In my cases both Python csv-module and LibreOffice calc failed processing the logfile for this reason.
### Rational

The actual data is irrelevant for checking links, so they can be stripped from the logging. To keep them matchable, store a cryptographic checksum instead. MD5 is a bit faster then SHA1 and should be okay for this case.

Data-URLs ar described at https://de.wikipedia.org/wiki/Data-URL#Format resp. https://en.wikipedia.org/wiki/Data_URI_scheme#Format

**Comment by htgoebel** [comment]
Addentum: If you point me to the place, where URLs are parsed, I volunteer to submit a pull-request.

**Comment by rap2hpoutre** [comment]
:+1: 
data:image problem is a false positive.

**Comment by htgoebel** [comment]
My issue is not about error logging, but logging in general.

**Comment by strouptl** [comment]
+1. Any movement on this @htgoebel ?

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists

**Comment by htgoebel** [comment]
Now see https://github.com/linkcheck/linkchecker/issues/98
