### ISSUE TITLE
Requests 2.6.2 seems to break linkchecker

### ISSUE THREAD

**Issue by cdown** [wummel/linkchecker#593]
I'm not sure exactly of the conditions, but notice the difference between the following CI runs:
- [Broken](https://travis-ci.org/cdown/chrisdown.name/builds/59774042)
- [Fixed](https://travis-ci.org/cdown/chrisdown.name/builds/59780955)

Builds were consistently failing with this problem until I downgraded back to 2.6.0. For now I've pinned requests to 2.6.0 in my Travis runs.

Feel free to let me know if you need any further information for debugging.

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists

**Comment by mgoodhand** [comment]
Great that the project has been revived.

For anyone looking for a very quick workaround, here's what I did:

`docker run -it python:2.7 bash`

Within Docker:

    1.  pip install linkchecker==9.3
    2.  sed -i.bak '/2.2.0/,+1 d' /usr/local/lib/python2.7/site-packages/linkcheck/__init__.py
    3.  diff -u /usr/local/lib/python2.7/site-packages/linkcheck/__init__.py.bak  /usr/local/lib/python2.7/site-packages/linkcheck/__init__.py
    4.  linkchecker

This just deletes the silly non-semver-aware check.

I haven't yet gone to the trouble of creating a Dockerfile, as hopefully the forked version of linkchecker will be pip installable soon.

**Comment by dpalic** [comment]
thx for feedback, could you please close this issue?

**Comment by mgoodhand** [comment]
I assume the last comment was directed at @cdown. I don't think I have power to close it.
