### ISSUE TITLE
Is it possible to ignore urls for syntax checking

### ISSUE THREAD

**Issue by ramonv** [wummel/linkchecker#595]
We've implemented some href="whatsapp://send?text=test" links in our sites. (upon click, they open up whatsapp on your mobile phone and sends a message.
LinkChecker says these links are invalid. (which is ofcourse correct behaviour looking at w3c).

But there's no way to ignore or disable syntax checking for these links. Adding them to --ignore-url doesnt work, cause the links still get checked for syntax.

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists

**Comment by gerdneuman** [comment]
@ramonv I guess this is to be merged into the fork at https://github.com/linkchecker/linkchecker/pull/180

**Comment by ramonv** [comment]
We are no longer using linkchecker. 

Since this repo is currently not maintained, i will close this issue. 
No idea if this issue is already fixed in the new repo, so if anyone finds this comment somewhere in the future, please check: https://github.com/linkcheck/linkchecker

**Comment by gerdneuman** [comment]
@ramonv just out of interest: What are you using instead for link checking?

**Comment by ramonv** [comment]
Currently nothing besides some output of Google Webmaster Tools.
The site which we used this for has grown in a way that crawling would take a couple of days.
