### ISSUE TITLE
Add possibility to warn for staging system links

### ISSUE THREAD

**Issue by dothebart** [wummel/linkchecker#602]
There may be URLs which are valid and reachable from the host linkchecker runs on, but should not be present on live content; I.e. links to test systems or staging environments.
Please add an option like --ignore-url which then in term will issue an error if a link matching these patterns is found.

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
