### ISSUE TITLE
How to uninstall on Linux?

### ISSUE THREAD

**Issue by Botster** [wummel/linkchecker#636]
I am bewildered as to why "setup.py" does not include an uninstall option. Do I have to search my entire system to try and find whatever various files were installed? Or reverse engineer "setup.py"?

How to I uninstall LinkChecker on Linux?

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists

**Comment by Botster** [comment]
Thank you for the response.

I gave up on this software over a year and a half ago.

**Comment by dpalic** [comment]
sadly the maintainer was not reachable.
Do you have found a alternative? If so which one?

**Comment by Botster** [comment]
No, I have not even looked for a practical alternative. When I found LinkChecker, I was looking for a customizable alternative to Xenu Link Sleuth for a particular project.
