### ISSUE TITLE
Exception when checking

### ISSUE THREAD

**Issue by stefanov-stefan** [wummel/linkchecker#637]
After checking couple hundred thousand links, it died on me twice: [http://screencast.com/t/Tqt8AX73l](url)

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists

**Comment by stefanov-stefan** [comment]
Thanks
