### ISSUE TITLE
9.3: can't set user-agent

### ISSUE THREAD

**Issue by jniggemann** [wummel/linkchecker#638]
using either the commandline option `--user-agent=` or the rcfile option `useragent=` results in linkchecker not working.
Output in html format only says:
>Beginne Prüfen am 2016-02-22 19:57:26+002
>
>Statistik
>Inhalte: 0 Bild, 0 Text, 0 Video, 0 Audio, 1 Anwendung, 0 E-Mail und 0 andere Inhalte.
>URL Längen: min=40, max=40, mittel=40
>
>Das war's. 1 Verknüpfung überprüft. 0 Warnungen gefunden. 0 Fehler gefunden.
>Beende Prüfen am 2016-02-22 19:57:27+002 (0.07 Sekunden) 

Commandline that works as expected:
`linkchecker http://mysite.org --check-extern -ohtml > ~/html/linkchecker.html`

Commandline that does _not_ work:
`linkchecker http://mysite.org --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10; rv:33.0) Gecko/20100101 Firefox/33.0" --check-extern -ohtml > ~/html/linkchecker.html`

**Comment by xrat** [comment]
It says that 1 link was checked. Could you check against a site where you have access to the access log? I assume that the user agent string was correctly set but access was blocked.

**Comment by jniggemann** [comment]
OMG, my bad. On my test site, Linkchecker is the only permitted useragent in robots.txt. I forgot to add the changed useragent to my robots.txt, so linkchecker stopped right away.
