### ISSUE TITLE
How to use plugins ?

### ISSUE THREAD

**Issue by tk421** [wummel/linkchecker#648]
How can you use the different plugins ? I cannot find the documentation to use it.

**Comment by Dale-May** [comment]
@wummel

How can one use the various plugins?

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
