### ISSUE TITLE
This program requires Python requests 2.2.0 or later.

### ISSUE THREAD

**Issue by chenjian158978** [wummel/linkchecker#654]
hello, my pc system is ubuntu16.04,and python 2.7.11+, python requests = 2.10.0.

1. download the source from [linkchecker](http://wummel.github.io/linkchecker/) 
2. then I install like `python setup.py install`
     then,
```
Installed /home/chenjian/.venv/python2.7/lib/python2.7/site-packages/LinkChecker-9.3-py2.7-linux-x86_64.egg
Processing dependencies for LinkChecker==9.3
Searching for requests==2.10.0
Best match: requests 2.10.0
Processing requests-2.10.0-py2.7.egg
requests 2.10.0 is already the active version in easy-install.pth

Using /home/chenjian/.venv/python2.7/lib/python2.7/site-packages/requests-2.10.0-py2.7.egg
Finished processing dependencies for LinkChecker==9.3
```
3.but I input like:
```
chenjian@chenjian-Rev-1-0:~/Downloads/LinkChecker-9.3$ linkchecker
This program requires Python requests 2.2.0 or later.
```
SO, where is the problem?

**Comment by e-anima** [comment]
Same Problem here on arch linux. 
I have "python-requests-2.10.0-1" installed
it seems the Version checking fails. I would gess because it checks for 10 and gets 1 < 2.

**Comment by anarcat** [comment]
duplicate of #649, please close.

**Comment by chenjian158978** [comment]
@anarcat thx a lot~
