### ISSUE TITLE
A problem with special characters in URL

### ISSUE THREAD

**Issue by jazz-soft** [wummel/linkchecker#668]
Found in LinkChecker 9.3 Released on 16.7.2014 on Windows 10

The page: http://art-hanoi.com/cgi-bin/toda?nguyen-bao-long-thong
Link on in the page:
&lt;a href=/cgi-bin/toda?nguyen-bao-thong-long-\* &gt;...&lt;/a&gt;
LinkChecker goes instead to:
http://art-hanoi.com/cgi-bin/toda?nguyen-bao-thong-long-%2A
and, no surprise, finds some problems.

Thanks,
sema

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
