### ISSUE TITLE
tests fail with "TypeError: hasattr(): attribute name must be string"

### ISSUE THREAD

**Issue by anarcat** [wummel/linkchecker#681]
It seems that tests fails on HEAD since 0ef00eea56a0ede54b4340ec9f7481ea622b8089. Here's the travis build log:

 https://travis-ci.org/wummel/linkchecker/builds/104276729

This affects all pull requests which also fail to pass tests.

**Comment by simevo** [comment]
note to self: to reproduce locally, on a clean debian sid lxc container install the prerequisites:

```
apt-get install git python python-setuptools python-dev python-requests gcc
```

then git clone this repo, build & and install:

```
git clone https://github.com/wummel/linkchecker.git
cd linkchecker
python setup.py sdist --manifest-only
python setup.py build
python setup.py install
```

NOTE: to make that work, I have to apply the patch 3b0ed398a70be03dad9bf48ca838f54d284341ea else I get (see #683):

```
error: can't copy 'doc/html/lccollection.qhc': doesn't exist or not a regular file
```

finally now launch the failing test:

```
cd tests
python -m unittest -v test_console
```

this does not show the stderr trace as in the travis build though ...

**Comment by anarcat** [comment]
moved to https://github.com/linkcheck/linkchecker/issues/7
