### ISSUE TITLE
Mac OSX Setup is Outdated

### ISSUE THREAD

**Issue by ghost** [wummel/linkchecker#691]
Ok, so I got through the following commands:

1. `xcode-select --install`
2. `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
3. `brew install python`
4. `brew install gettext`
5. `brew link --force gettext`
6. `curl -O http://peak.telecommunity.com/dist/ez_setup.py`
7. `sudo python ez_setup.py -U setuptools`
8. `sudo easy_install -U py2app`
9. `git clone git@github.com:wummel/linkchecker.git linkchecker`
10. `cd linkchecker`

However, when I got to: `pip install -r requirements.txt --use-mirrors`, it was broken, due to `--use-mirrors` being deprecated. So I substituted in `--no-cache-dir` as suggested by StackOverflow. Which did something...

I then went to complete the `make app` command, but got an error: `make: *** No rule to make target `app'.  Stop.`

I tried `make linkchecker`, `make setup.py`, and `make install-rpm.sh`, but got the message that there is nothing to be done for any of them.

What do I do to finish this last step and get the .dmg file?

EDIT: I'm not used to Mac, only been on one for a month for my new job. Maybe I'm missing something extremely obvious here? I tried `sudo` and no dice.

**Comment by ghost** [comment]
Just followed user @bootstraponline old post [here](https://github.com/wummel/linkchecker/issues/474). Installing the extra modules he did and running: `make localbuild` did something...but did not create a .dmg file.

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
