### ISSUE TITLE
Icon for Windows executable is incorrect

### ISSUE THREAD

**Issue by goozak** [wummel/linkchecker#696]
The correct icon is used for the main window of the app (bottom one in the screenshot below), but not for the executable (linkchecker-gui.exe)  — which is the one used by Windows in the task bar.

I guess it doesn't really matter for the command-line executable (linkchecker.exe).

![screenshot - 15-12-16 11_18_35](https://cloud.githubusercontent.com/assets/454810/21232178/cec93506-c2b8-11e6-869b-c51adf5f4118.png)

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues

**Comment by goozak** [comment]
Issue [posted](https://github.com/linkcheck/linkchecker/issues/99) in 'new' repo.
