### ISSUE TITLE
Python 3 not supported

### ISSUE THREAD

**Issue by peterjc** [wummel/linkchecker#698]
The README says "Python 2.7.2 or later is needed." which implies Python 3 should work.

However, installation under Python 3 fails, first problem the issue logged as #671.

In the short term the README should be updated to say something like "Python 2.7.2 or later is needed (but Python 3 is not yet supported)."

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues

**Comment by peterjc** [comment]
Fixed in the new fork by https://github.com/linkcheck/linkchecker/pull/90
