### ISSUE TITLE
build is failing according to readme

### ISSUE THREAD

**Issue by matkoniecz** [wummel/linkchecker#705]
https://github.com/wummel/linkchecker#linkchecker

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues

**Comment by matkoniecz** [comment]
> report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues

Why? It is clearly not present there.
