### ISSUE TITLE
Do not scan SSL

### ISSUE THREAD

**Issue by mrkaban** [wummel/linkchecker#709]
Hello, Thank you for such a good program! I added it to my site for free software. Here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%81%D0%B5%D1%82%D1%8C,-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/linkchecker-%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%B1%D0%B8%D1%82%D1%8B%D1%85-%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D0%BA-%D0%BD%D0%B0-%D1%81%D0%B0%D0%B9%D1%82%D0%B5.html). I really like it! very comfortable!

Before that, I was not looking for a working link on the website using the LinkChecker. But now moved the site to https and references all changed on the relative address, regardless of the protocol (eg, //sitename.ru/image.jpg). And now, the program for all those pages produces an error, although a working link.

Also, the program swears on all internal links with https.

How to solve this problem? Screenshot attached
![1](https://cloud.githubusercontent.com/assets/14289360/22623943/9dd4d6bc-eb9e-11e6-9b0f-616329912e33.jpg)

**Comment by anarcat** [comment]
if you wish to get support, please see issue #708 and report your issue against the real linkchecker project.

please close this issue so that #708 stays on top of the list - thanks!

**Comment by mrkaban** [comment]
I have found the solution myself. In the settings there is a configuration file. It is a point of checking ssl certificate, it must be disabled, that is put = 0.

**Comment by anarcat** [comment]
@mrkaban thanks so much!
