### ISSUE TITLE
Stopped finding broken links

### ISSUE THREAD

**Issue by mrkaban** [wummel/linkchecker#725]
Hello, there is a site [https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai), used to find broken links on it, but now has stopped. It seems that I did not change anything in the settings of the program, not on the site.

The following important parameters are set in the configuration:
sslverify=0
allowedschemes=http,https

Prompt please, I can not understand. Very handy program!

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
