### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by chrissie52** [wummel/linkchecker#734]
Hi,
If I will use LinkChecker 9.3 in GUI on our https-site, I get an error:
Error: SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

Our hosting partner is 1&1, we have there new a certificate on this site.

What can I do?

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
