### ISSUE TITLE
Let's Encrypt SSL Certificate

### ISSUE THREAD

**Issue by ReLater** [wummel/linkchecker#736]
I'm using Let's Encrypt SSL certificates for several domains at provider All-Inkl.

All scans with LinkChecker 9.3 / WIN 10 end up with messages like

> Error: SSLError: hostname 'ghsvs.de' doesn't match either of '*.kasserver.com', 'kasserver.com'

LinkChecker-9.3.exe downloaded here: https://wummel.github.io/linkchecker/

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
