### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by jjnxpct** [wummel/linkchecker#739]
When trying to check links on a website with a SSL certificate (https://) we get an error like this:

**Error: SSLError: hostname ..... doesn't match....**

I know the SSL is installed correctly. This happens on more sites with https / SSL. 

De domainname on the certificate is checked against the hostname of the (shared) server I believe. And that won't match. But that doesn't mean there is an SSL error.

Any thoughts on this? Is this a bug?

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues

**Comment by jjnxpct** [comment]
OK, thanks!
