### ISSUE TITLE
Filtering out LinkChecker results?

### ISSUE THREAD

**Issue by HomeDipo** [wummel/linkchecker#744]
Hello,

I am new to LinkChecker so this may be a silly question, but is it possible to have it search for a specific section of the site only?

Example:
Is there a way for it to only show links that start with http://www.example.org/myhomepage/?

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues

**Comment by HomeDipo** [comment]
Thank you!
