### ISSUE TITLE
Is this application supported to be used on a Windows 10 machine?

### ISSUE THREAD

**Issue by y4n0** [wummel/linkchecker#747]
My question is in the title, thanks! :)

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues

**Comment by dpalic** [comment]
please close this issue, to avoid new users to post reports here

**Comment by y4n0** [comment]
Thanks for taking your time to help and sorry for not closing it sooner...
