### ISSUE TITLE
Ignore URL not working

### ISSUE THREAD

**Issue by sussidio** [wummel/linkchecker#748]
Hi,

I add search patterns to ignore in the Options, for example the below:

```
https://www.*
*/CACHE/*
*/static/*
*/frontend/*
```

The first ignore pattern works, but the rest do not. Can you please advise if I'm doing something wrong or if it is an issue with the applications.

Cheers,

Ben

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues

**Comment by dpalic** [comment]
please close this issue, to avoid new users to post reports here

**Comment by dpalic** [comment]
could you please close this issue?

**Comment by sussidio** [comment]
This issue is closed due to Line Checker no longer supporting.

**Comment by sussidio** [comment]
Issue is closed.

Cheers,

Ben (@bfausti <https://instagram.com/bfausti/>)
