### ISSUE TITLE
HTTPS and ErrorSSL

### ISSUE THREAD

**Issue by toplisek** [wummel/linkchecker#749]
I'm not sure but I can not check links at HTTPS websites.
Is this possible to be fixed? I like this software as it one of the best but HTTPs seems not to be supported. How to validate links when using HTTPS secured links.
Thank you.

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
