### ISSUE TITLE
Error: SSLError: hostname 'xxxx' doesn't match either of '*.one.com', 'one.com'

### ISSUE THREAD

**Issue by ajtruckle** [wummel/linkchecker#751]
When I run my site for link checking:

www.publictalksoftware.co.uk/help-msa/index.html

It comes up with lots of errors::

> Error: SSLError: hostname 'www.publictalksoftware.co.uk' doesn't match either of '*.one.com', 'one.com'

One.com is my domain provider. I am confused.

Andrew

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
