### ISSUE TITLE
Cannot save

### ISSUE THREAD

**Issue by ParkerD13** [wummel/linkchecker#752]
Hi, when I try to save a project or to save results, the file dialogue pops up but nothing happens when I click "save". No error or anything, I can only click abort. I tried different file formats and changed the file name. That all did not change anything.
I guess I have about 120 to 150 results on the list. 
Linkchecker 9.3 on Win7 pro (Python 2.7.8, Requests 2.2.1, not the portable version).

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
