### ISSUE TITLE
LinkChecker internal error

### ISSUE THREAD

**Issue by jeremybickerstaffe** [wummel/linkchecker#765]
I can't get LinkChecker to work at all.
Steps to reproduce:
* Install LinkChecker 9.3 on Windows 10
* Type any URL into the box
* Click "Start"
* Result: LinkChecker internal error

********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "linkcheck\gui\checker.pyo", line 45, in run
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\checker.py
    -- code not available --
  File "linkcheck\director\__init__.pyo", line 34, in check_urls
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\director\__init__.py
    -- code not available --
  File "linkcheck\director\aggregator.pyo", line 82, in visit_loginurl
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\director\aggregator.py
    -- code not available --
  File "requests\sessions.pyo", line 395, in get
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\requests\sessions.py
    -- code not available --
  File "requests\sessions.pyo", line 383, in request
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\requests\sessions.py
    -- code not available --
  File "requests\sessions.pyo", line 486, in send
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\requests\sessions.py
    -- code not available --
  File "requests\adapters.pyo", line 385, in send
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\requests\adapters.py
    -- code not available --
SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Requests: 2.2.1
Qt: 4.8.6 / PyQt: 4.11
Modules: QScintilla, Sqlite
Local time: 2019-03-21 14:52:23+001
sys.argv: ['C:\\Program Files (x86)\\LinkChecker\\linkchecker-gui.exe']
Default locale: ('en', 'cp1252')

 ******** LinkChecker internal error, over and out ********

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues

**Comment by jeremybickerstaffe** [comment]
Thanks. I was going to report this error at your new site but I've just tried Linkchecker again and didn't get this problem so will just close this issue.
